name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: Generate documentation
    steps:
      - uses: actions/checkout@v2

      # Generate documentation
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: Documentation~/docfx.json

      # Publish generated site using GitHub Pages
      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Documentation~/_site
          force_orphan: true